custosortosintesev2/src/main/java/br/com/ortosintese/custos/models/Componente.java
package br.com.ortosintese.custos.models;

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class Componente {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	@OneToOne
	private Produto produto;
	@OneToOne
	private Produto produtoFilho;
	private BigDecimal quantidade;

	public Produto getProdutoFilho() {
		return produtoFilho;
	}

	public Componente setProdutoFilho(Produto produtoFilho) {
		this.produtoFilho = produtoFilho;
		return this;
	}

	public BigDecimal getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(BigDecimal quantidade) {
		this.quantidade = quantidade;
	}

	public BigDecimal getCustoTotal() {
		return produtoFilho.getCusto().multiply(quantidade).setScale(2);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((produtoFilho == null) ? 0 : produtoFilho.hashCode());
		result = prime * result + ((quantidade == null) ? 0 : quantidade.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Componente other = (Componente) obj;
		if (produtoFilho == null) {
			if (other.produtoFilho != null)
				return false;
		} else if (!produtoFilho.equals(other.produtoFilho))
			return false;
		if (quantidade == null) {
			if (other.quantidade != null)
				return false;
		} else if (!quantidade.equals(other.quantidade))
			return false;
		return true;
	}
}

custosortosintesev2/src/main/java/br/com/ortosintese/custos/models/Processo.java
package br.com.ortosintese.custos.models;

import java.math.BigDecimal;
import java.math.RoundingMode;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class Processo {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	@OneToOne
	private Produto produto;
	private String fornecedor;
	private String descricao;
	private double tempo;
	private BigDecimal custoPorHora;
	private BigDecimal valor;
	private long lote = 1;
	private String observacao;
	private TipoProcesso tipoProcesso = TipoProcesso.INTERNO;

	public Processo(String fornecedor, String descricao) {
		this.fornecedor = fornecedor;
		this.descricao = descricao;
	}

	public Processo() {
	}

	public String getDetalhes() {
		String detalhes = new String();
		if (tipoProcesso.equals(TipoProcesso.INTERNO)) {
			detalhes += "Tempo: " + Ferramentas.tempoDoubleToHora(tempo) + " Custo por Hora: " + custoPorHora + " - "
					+ observacao;
		} else {
			detalhes += observacao;
		}
		return detalhes;
	}

	@Override
	public String toString() {
		return "Processo [fornecedor=" + fornecedor + ", descricao=" + descricao + ", tempo=" + tempo
				+ ", custoPorHora=" + custoPorHora + ", valor=" + valor + ", lote=" + lote + ", observacao="
				+ observacao + "]";
	}

	public String getFornecedor() {
		return fornecedor;
	}

	public Processo setFornecedor(String fornecedor) {
		this.fornecedor = fornecedor;
		return this;
	}

	public String getDescricao() {
		return descricao;
	}

	public Processo setDescricao(String descricao) {
		this.descricao = descricao;
		return this;
	}

	public double getTempo() {
		return tempo;
	}

	public void setTempo(double tempo) {
		this.tempo = tempo;
	}

	public BigDecimal getCustoPorHora() {
		return custoPorHora;
	}

	public void setCustoPorHora(BigDecimal bigDecimal) {
		this.custoPorHora = bigDecimal;
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public long getLote() {
		return lote;
	}

	public void setLote(long lote) {
		this.lote = lote;
	}

	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	public TipoProcesso getTipoProcesso() {
		return tipoProcesso;
	}

	public void setTipoProcesso(TipoProcesso tipoProcesso) {
		this.tipoProcesso = tipoProcesso;
	}

	public BigDecimal getCusto() {
		if (tipoProcesso.equals(TipoProcesso.INTERNO)) {
			return custoPorHora.multiply(new BigDecimal(tempo)).divide(new BigDecimal(lote), 2).setScale(2,
					RoundingMode.HALF_EVEN);
		} else {
			return valor.divide(new BigDecimal(lote), 2).setScale(2, RoundingMode.HALF_EVEN);
		}
	}

	public BigDecimal getCustoTotal() {
		return getCusto().multiply(new BigDecimal(lote)).setScale(2, RoundingMode.HALF_EVEN);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((custoPorHora == null) ? 0 : custoPorHora.hashCode());
		result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
		result = prime * result + ((fornecedor == null) ? 0 : fornecedor.hashCode());
		result = prime * result + (int) (lote ^ (lote >>> 32));
		result = prime * result + ((observacao == null) ? 0 : observacao.hashCode());
		long temp;
		temp = Double.doubleToLongBits(tempo);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((tipoProcesso == null) ? 0 : tipoProcesso.hashCode());
		result = prime * result + ((valor == null) ? 0 : valor.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Processo other = (Processo) obj;
		if (custoPorHora == null) {
			if (other.custoPorHora != null)
				return false;
		} else if (!custoPorHora.equals(other.custoPorHora))
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		if (fornecedor == null) {
			if (other.fornecedor != null)
				return false;
		} else if (!fornecedor.equals(other.fornecedor))
			return false;
		if (lote != other.lote)
			return false;
		if (observacao == null) {
			if (other.observacao != null)
				return false;
		} else if (!observacao.equals(other.observacao))
			return false;
		if (Double.doubleToLongBits(tempo) != Double.doubleToLongBits(other.tempo))
			return false;
		if (tipoProcesso != other.tipoProcesso)
			return false;
		if (valor == null) {
			if (other.valor != null)
				return false;
		} else if (!valor.equals(other.valor))
			return false;
		return true;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}
}

custosortosintesev2/src/main/java/br/com/ortosintese/custos/models/Produto.java
package br.com.ortosintese.custos.models;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Calendar;
import java.util.Iterator;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import org.springframework.format.annotation.DateTimeFormat;

import br.com.ortosintese.custos.dao.ProdutoDAO;

@Entity
public class Produto {

	@Id
	private String codigo;
	private String descricao;
	private float markup = 2.0f;
	@OneToOne
	private MateriaPrima materiaPrima;
	private double qtdMateriaPrima;
	@OneToMany(fetch = FetchType.EAGER)
	private Set<Processo> processos;
	@OneToMany(fetch = FetchType.EAGER)
	private Set<Componente> componentes;
	@DateTimeFormat
	private Calendar revisao;

	public BigDecimal getCusto() {
		BigDecimal custoTotal = new BigDecimal(0);
		custoTotal = custoTotal.add(getCustoMateriaPrima());
		custoTotal = custoTotal.add(getCustoProcessos());
		custoTotal = custoTotal.add(getCustoComponentes());
		return custoTotal.setScale(2, RoundingMode.HALF_EVEN);
	}

	public BigDecimal getCustoComponentes() {
		BigDecimal custoTotalComponentes = new BigDecimal(0);

		for (Componente componente : componentes) {
			custoTotalComponentes = custoTotalComponentes.add(componente.getCustoTotal());
		}

		return custoTotalComponentes;
	}

	public BigDecimal getCustoMateriaPrima() {
		try {
			return materiaPrima.getCustoPorUM().multiply(new BigDecimal(qtdMateriaPrima)).setScale(2,
					RoundingMode.HALF_EVEN);
		} catch (Exception e) {
			return new BigDecimal(0).setScale(2, RoundingMode.HALF_EVEN);
		}
	}

	public BigDecimal getCustoProcessos() {
		BigDecimal custoTotalProcessos = new BigDecimal(0);

		for (Processo processo : processos) {
			custoTotalProcessos = custoTotalProcessos.add(processo.getCusto());
		}

		return custoTotalProcessos;
	}

	public String getCodigo() {
		return codigo;
	}

	public Produto setCodigo(String codigo) {
		this.codigo = codigo;
		return this;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public MateriaPrima getMateriaPrima() {
		return materiaPrima;
	}

	public Produto setMateriaPrima(MateriaPrima materiaPrima) {
		this.materiaPrima = materiaPrima;
		return this;
	}

	public double getQtdMateriaPrima() {
		return qtdMateriaPrima;
	}

	public void setQtdMateriaPrima(double qtdMateriaPrima) {
		this.qtdMateriaPrima = qtdMateriaPrima;
	}

	public Set<Processo> getProcessos() {
		return processos;
	}

	public void setProcessos(Set<Processo> processos) {
		this.processos = processos;
	}

	public Set<Componente> getComponentes() {
		return componentes;
	}

	public void setComponentes(Set<Componente> componentes) {
		this.componentes = componentes;
	}

	public Calendar getRevisao() {
		return revisao;
	}

	public void setRevisao(Calendar revisao) {
		this.revisao = revisao;
	}

	@Override
	public String toString() {
		return "Produto [codigo=" + codigo + ", descricao=" + descricao + ", materiaPrima=" + materiaPrima
				+ ", qtdMateriaPrima=" + qtdMateriaPrima + ", processos=" + processos + ", componentes=" + componentes
				+ ", revisao=" + revisao + "]";
	}

	public void addProcesso(Processo processo) {
		if (!processos.contains(processo)) {
			processos.add(processo);
		} else {
			processos.remove(processo);
			processos.add(processo);
		}
	}

	public void removeProcesso(String fornecedor, String descricao) {
		Iterator<Processo> iterator = processos.iterator();
		while (iterator.hasNext()) {
			Processo tempProcesso = iterator.next();
			if (tempProcesso.getFornecedor().equals(fornecedor)) {
				if (tempProcesso.getDescricao().equals(descricao)) {
					iterator.remove();
				}
			}
		}
	}

	public void alteraProcesso(Processo processoAntigo, Processo processoNovo) {
		Iterator<Processo> iterator = processos.iterator();
		while (iterator.hasNext()) {
			Processo processo = iterator.next();
			if (processo.getFornecedor().equals(processoAntigo.getFornecedor())) {
				if (processo.getDescricao().equals(processoAntigo.getDescricao())) {
					iterator.remove();
				}
			}
		}
		processos.add(processoNovo);
	}

	public void addComponente(Componente componente) {
		componentes.add(componente);
	}

	public void removeComponente(Componente componente) {
		componentes.remove(componente);
	}

	public void removeMateriaPrima() {
		materiaPrima = null;
		qtdMateriaPrima = 0;
	}

	public Processo getProcesso(String fornecedor, String descricao) {
		for (Processo processo : processos) {
			if (processo.getFornecedor().equals(fornecedor)) {
				if (processo.getDescricao().equals(descricao)) {
					return processo;
				}
			}
		}
		return null;
	}

	public void atualizaRevisao() {
		this.revisao = Calendar.getInstance();
	}

	public BigDecimal getPreco(ProdutoDAO dao, String mercado) {
		BigDecimal preco = dao.getPreco(codigo, mercado);
		return preco;
	}

	public boolean getCustoZero() {
		return (getCusto().equals(new BigDecimal(0).setScale(2))) ? true : false;
	}

	public float getMarkup() {
		return markup;
	}

	public void setMarkup(float markup) {
		this.markup = markup;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigo == null) ? 0 : codigo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Produto other = (Produto) obj;
		if (codigo == null) {
			if (other.codigo != null)
				return false;
		} else if (!codigo.equals(other.codigo))
			return false;
		return true;
	}
}

custosortosintesev2/src/main/java/br/com/ortosintese/custos/controllers/HomeController.java
package br.com.ortosintese.custos.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class HomeController {
	
	@RequestMapping("/")
	public String home() {
		return "home";
	}
}

custosortosintesev2/src/main/webapp/WEB-INF/views/produtos/atualizarPrecosForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
    
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<c:import url="/WEB-INF/views/_common/bootstrap.jsp"/>
	<link rel="stylesheet" href="<c:url value="/resources/css/acoes.css"/>">
	<link rel="stylesheet" href="<c:url value="/resources/css/detalhe.css"/>">
</head>
<body>
	<c:import url="/WEB-INF/views/_common/nav.jsp"/>
	<c:import url="/WEB-INF/views/_common/acoesProdutos.jsp"/>
	<section id="main" class="container">
		<form class="form" method="post">
			<div class="form-group">
				<label>Mercado</label>
				<select class="form-control" name="mercado">
					<option value="MI">Interno</option>
					<option value="ME">Externo</option>
				</select>
			</div>
			<div class="form-group">
				<label>Precos</label>
				<textarea class="form-control" rows="20" cols="100" name="precos"></textarea>
			</div>
			<div class="form-group">
				<button class="btn btn-default" type="submit">Enviar</button>
			</div>
		</form>
	</section>
</body>
</html>

custosortosintesev2/src/main/webapp/WEB-INF/views/produtos/criticos.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<c:import url="/WEB-INF/views/_common/bootstrap.jsp"/>
		<link rel="stylesheet" href="<c:url value="/resources/css/acoes.css"/>">
	</head>
	<body>
		<c:import url="/WEB-INF/views/_common/nav.jsp"/>
		<c:import url="/WEB-INF/views/_common/acoesProdutos.jsp"/>
		<section id="main" class="container-fluid">
			<h2>Produtos Críticos</h2>
			<div class="row">
				<div class="col-md-2">
					<form:form id="form-procurar" class="form" action="${s:mvcUrl('PC#lista').build()}" method="get">
						<div class="form-group">
							<label>Codigo</label>
							<input class="form-control" type="text" name="codigo" autofocus>
						</div>
						<div class="form-group">
							<label>Descricao</label>
							<input class="form-control" type="text" name="descricao">
						</div>
						<button class="btn btn-default" type="submit">Filtrar</button>
					</form:form>
				</div>
				<div class="table-responsive col-md-10">
					<table class="table">
						<thead>
							<tr>
								<th>Produto</th>
								<th>Descricao</th>
								<th>Custo Total</th>
								<th>Ultima Revisao</th>
								<th>Preco MI</th>
								<th>Preco ME</th>
							</tr>
						</thead>
						<tbody>
							<c:forEach var="produto" items="${produtos}">
								<tr>
									<td><a href="${s:mvcUrl('PC#detalhe').build()}=${produto.codigo}">${produto.codigo}</a></td>
									<td>${produto.descricao}</td>
									<td>${produto.custo}</td>
									<td>${dateFormat.format(produto.revisao.time)}</td>
									<c:if test="${not empty produto.getPreco(dao, 'MI') and not produto.custoZero}">
										<td>Preco MI: R$ ${produto.getPreco(dao, 'MI')} (Mkup: ${produto.getPreco(dao, 'MI') / produto.custo})</td>
									</c:if>
									<c:if test="${not empty produto.getPreco(dao, 'ME') and not produto.custoZero}">
										<td>Preco ME: U$ ${produto.getPreco(dao, 'ME')} (Mkup: ${produto.getPreco(dao, 'ME') * 3 / produto.custo})</td>
									</c:if>
								</tr>
							</c:forEach>
						</tbody>
					</table>
				</div>
			</div>
		</section>
	</body>
</html>

custosortosintesev2/src/main/webapp/WEB-INF/views/produtos/detalhe.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<c:import url="/WEB-INF/views/_common/bootstrap.jsp"/>
		<link rel="stylesheet" href="<c:url value="/resources/css/detalhe.css"/>">
	</head>
	<body>
		<c:import url="/WEB-INF/views/_common/nav.jsp"/>
		<c:import url="/WEB-INF/views/_common/acoesProdutos.jsp"/>
		<section id="main" class="container">
			<div class="row">
				<div class="row col-md-8">
					<h2 class="col-md-12">${produto.codigo} - ${produto.descricao}</h2>
					<a id="botao-impressao" class="btn btn-default" href="${s:mvcUrl('PC#impressao').arg(0, produto.codigo).build()}">Impressão</a>
					<a id="botao-danger" class="btn btn-danger" href="${s:mvcUrl('PC#excluirProduto').arg(0, produto.codigo).build()}">Excluir Produto!</a>
				</div>
				<div class="row col-md-4">
					<p class="custo-total col-md-12">Custo Total: R$ ${produto.custo}</p>
					<c:if test="${not empty produto.getPreco(dao, 'MI') and not produto.custoZero}">
						<p class="col-md-12">Preco MI: R$ ${produto.getPreco(dao, 'MI')} (Mkup: ${produto.getPreco(dao, 'MI') / produto.custo})</p>
					</c:if>
					<c:if test="${not empty produto.getPreco(dao, 'ME') and not produto.custoZero}">
						<p class="col-md-12">Preco ME: U$ ${produto.getPreco(dao, 'ME')} (Mkup: ${produto.getPreco(dao, 'ME') * 3 / produto.custo})</p>
					</c:if>
					<p class="col-md-12">Ultima revisão: ${dateFormat.format(produto.revisao.time)}</p>
				</div>
			</div>
			<form:form class="form" action="${s:mvcUrl('PC#alteraDescricao').build()}" method="post" commandName="produto">
				<form:input type="hidden" value="${produto.codigo}" path="codigo"/>
				<div class="row">
					<div class="form-group col-md-10">
						<label>Descricao</label>
						<form:input class="form-control" path="descricao"/>
					</div>
					<div class="form-group col-md-2">
						<label>MarkUp Mínimo</label>
						<form:input class="form-control" path="markup"/>
					</div>
				</div>
				<button class="btn btn-default" type="submit">Alterar</button>
			</form:form>
			<form:form id="form-materia-prima" class="form" action="${s:mvcUrl('PC#alteraMateriaPrima').build()}" method="post" commandName="produto">
				<form:input type="hidden" path="codigo"/>
				<div class="row">
					<div class="form-group col-xs-12 col-md-8">
						<label>Materia Prima</label>
						<form:select class="form-control" path="materiaPrima.id">
						<option value=""></option>
							<c:forEach var="materiaPrima" items="${materiasPrimas}">
								<option value="${materiaPrima.id}" <c:if test="${materiaPrima.id eq produto.materiaPrima.id}">selected</c:if>>${materiaPrima.descricao} - Un: ${materiaPrima.unidadeMedida} - Custo: R$ ${materiaPrima.custoPorUM}</option>
							</c:forEach>
						</form:select>
					</div>
					<div class="form-group col-xs-6 col-md-2">
						<label>Qtd MP</label>
						<form:input class="form-control" path="qtdMateriaPrima"/>
					</div>
					<div class="form-group col-xs-6 col-md-2">
						<label>Valor MP</label>
						<input class="form-control" value="R$ ${produto.custoMateriaPrima}" disabled></input>
					</div>
				</div>
				<button class="btn btn-default" type="submit">Alterar</button>
				<a class="btn btn-default" href="${s:mvcUrl('PC#removeMateriaPrima').arg(0, produto.codigo).build()}">Remover</a>
			</form:form>
			<h2>Processos</h2>
			<a href="${s:mvcUrl('PC#processoForm').arg(0, produto.codigo).build()}">Adicionar Processo</a>
			<table class="table">
				<thead>
					<tr>
						<th>Fornecedor</th>
						<th>Descricao</th>
						<th>Valor</th>
						<th>Lote</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach var="processo" items="${produto.processos}" varStatus="loop">
						<tr title="${processo.detalhes}">
							<td>${processo.fornecedor}</td>
							<td>${processo.descricao}</td>
							<td>${processo.custoTotal}</td>
							<td>${processo.lote}</td>
							<td>${processo.custo}</td>
							<td>
								<div class="dropdown">
						          	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu${loop.index}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						            	Acoes
						            	<span class="caret"></span>
						          	</button>
						          	<ul class="dropdown-menu" aria-labelledby="dropdownMenu${loop.index}">
							            <li><a href="${s:mvcUrl('PC#alteraProcessoForm').arg(0, processo.id).build()}">Alterar</a></li>
							            <li><a href="${s:mvcUrl('PC#removeProcesso').arg(0, processo.id).build()}">Remover</a></li>
						          	</ul>
						        </div>
							</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
			<h2>Componentes</h2>
			<a href="${s:mvcUrl('PC#cadastraComponenteForm').arg(0, produto.codigo).build()}">Adicionar Componente</a>
			<table class="table">
				<thead>
					<tr>
						<th>Código</th>
						<th>Descricao</th>
						<th>Custo</th>
						<th>Quantidade</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach var="componente" items="${produto.componentes}">
						<tr>
							<td><a href="${s:mvcUrl('PC#detalhe').arg(0, componente.produtoFilho.codigo).build()}">${componente.produtoFilho.codigo}</a></td>
							<td>${componente.produtoFilho.descricao}</td>
							<td>${componente.produtoFilho.custo}</td>
							<td>${componente.quantidade}</td>
							<td>${componente.custoTotal}</td>
							<td>
								<div class="dropdown">
						          	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu${loop.index}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						            	Acoes
						            	<span class="caret"></span>
						          	</button>
						          	<ul class="dropdown-menu" aria-labelledby="dropdownMenu${loop.index}">
							            <li><a href="${s:mvcUrl('PC#alteraComponenteForm').arg(0, produto.codigo).arg(1, componente.produtoFilho.codigo).arg(2, componente.quantidade).build()}">Alterar</a></li>
							            <li><a href="${s:mvcUrl('PC#removeComponente').arg(0, produto.codigo).arg(1, componente.produtoFilho.codigo).build()}">Remover</a></li>
						          	</ul>
						        </div>
							</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</section>
	</body>
</html>

custosortosintesev2/src/main/webapp/WEB-INF/views/produtos/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<c:import url="/WEB-INF/views/_common/bootstrap.jsp"/>
		<link rel="stylesheet" href="<c:url value="/resources/css/acoes.css"/>"/>
	</head>
	<body>
		<c:import url="/WEB-INF/views/_common/nav.jsp"/>
		<c:import url="/WEB-INF/views/_common/acoesProdutos.jsp"/>
		<section id="main" class="container">
			<h2>Últimas Atualizações</h2>
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr>
							<th>Codigo</th>
							<th>Descricao</th>
							<th>Custo Total</th>
							<th>Data</th>
							<th>Preco MI</th>
							<th>Preco ME</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach var="produto" items="${produtos}">
							<tr>
								<td><a href="${s:mvcUrl('PC#detalhe').arg(0, produto.codigo).build()}">${produto.codigo}</a></td>
								<td>${produto.descricao}</td>
								<td>R$ ${produto.custo}</td>
								<td>Ultima revisão: ${dateFormat.format(produto.revisao.time)}</td>
								<c:if test="${not empty produto.getPreco(dao, 'MI') and not produto.custoZero}">
									<td>Preco MI: R$ ${produto.getPreco(dao, 'MI')} (Mkup: ${produto.getPreco(dao, 'MI') / produto.custo})</td>
								</c:if>
								<c:if test="${not empty produto.getPreco(dao, 'ME') and not produto.custoZero}">
									<td>Preco ME: U$ ${produto.getPreco(dao, 'ME')} (Mkup: ${produto.getPreco(dao, 'ME') * 3 / produto.custo})</td>
								</c:if>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</div>
		</section>
	</body>
</html>